### ISSUE TITLE
Firefox problem

### ISSUE THREAD

**Issue by PhilipPeake** [codezero-be/responsive-nav#1]
Firefox 8.0.1 on OS/X 10.10.2

When the width is reduced and the menu switches the the collapsed view, the "hamburger" is overlaid with the letters "Me".

I don't see this on any other browser that I have tried.

![image](https://cloud.githubusercontent.com/assets/11996597/7205730/38b96804-e4e0-11e4-9e0f-44b792dfeb48.png)

**Comment by ivanvermeyen** [comment]
Does it help if you increase the `padding-left` of the `.nav-button`?
https://github.com/codezero-be/responsive-nav/blob/master/assets/sass/_layout-base.scss#L38

This should push the text "Menu" out of sight (overflow hidden).
I only have an older OSX virtual machine to test it, but I didn't get the issue there.

**Comment by ivanvermeyen** [comment]
Ok, I noticed too late that you are using an old version of FF (current version is 37).
I installed that one and now I see it too. 
It seems the trick with `padding-left` and `overflow: hidden` doesn't work here...

https://github.com/codezero-be/responsive-nav/blob/master/assets/sass/_layout-base.scss#L33-L57

If I delete this line from `.nav-button`:

    padding-left: 2.4rem; // Hide "Menu" text

and these lines from the `:before`:

    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;

... it seems to work everywhere, also on FF 8.

I'll make the changes and push it. :)

**Comment by PhilipPeake** [comment]
Guess what? As soon as I entered that problem, the symptom went away, and I can’t re-create it!

If I hadn’t taken a screen shot, I would think I imagined it.

Forget it for now. If it re-occurs I will let you now, and try incra=easing the padding.

Philip

**Comment by ivanvermeyen** [comment]
Hehe, you were'nt imagining it, I was able to reproduce it. ;)
I pushed the fix, so it should be ok now :)
Thanks for the feedback!
